### ISSUE TITLE
bookmarks toolbar not deiconized on startup

### ISSUE THREAD

**Issue by robcee** [robcee/bookmarks-deiconizer#3]

**Comment by robcee** [comment]
fixed in 2.1.1

**Comment by maartenhunink** [comment]
This issue came back, using version 2.2.2 on Snow Leopard. With me it had to do with a conflicting add-on, in my case Test Pilot 1.1

**Comment by robcee** [comment]
ah, thanks for the feedback. That's good info. I was suspecting there was a conflict with something else.
